Document: pycharm-community
Title: Debian pycharm-community Manual
Author: <insert document author here>
Abstract: This manual describes what pycharm-community is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pycharm-community/pycharm-community.sgml.gz

Format: postscript
Files: /usr/share/doc/pycharm-community/pycharm-community.ps.gz

Format: text
Files: /usr/share/doc/pycharm-community/pycharm-community.text.gz

Format: HTML
Index: /usr/share/doc/pycharm-community/html/index.html
Files: /usr/share/doc/pycharm-community/html/*.html
